// <auto-generated />
using Listenarr.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Listenarr.Infrastructure.Migrations
{
    [DbContext(typeof(ListenArrDbContext))]
    [Migration("20251125103000_AddDownloadFinalizationSettingsToApplicationSettings")]
    partial class AddDownloadFinalizationSettingsToApplicationSettings
    {
    }
}
