// <auto-generated />
using System;
using Listenarr.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listenarr.Api.Migrations
{
    [DbContext(typeof(ListenArrDbContext))]
    [Migration("20251028180000_AddNotificationSettingsToApplicationSettings")]
    partial class AddNotificationSettingsToApplicationSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Listenarr.Api.Models.ApiConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RateLimitPerMinute")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApiConfigurations");
                });

            modelBuilder.Entity("Listenarr.Api.Models.ApplicationSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedFileExtensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudnexusApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedFileAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableCoverArtDownload")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableMetadataProcessing")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnabledNotificationTriggers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileNamingPattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrentDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PollingIntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferUsDomain")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowCompletedExternalDownloads")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsProxyHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsProxyPassword")
                        .HasColumnType("TEXT");

                    b.Property<int>("UsProxyPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsProxyUsername")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseUsProxy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings");
                });

            // ...existing code for other entities is intentionally omitted in the designer to keep file concise
#pragma warning restore 612, 618
        }
    }
}
