using Listenarr.Api.Models;
using System.Text.Json;

namespace Listenarr.Api.Services
{
    public interface IStartupConfigService
    {
        StartupConfig? GetConfig();
        Task ReloadAsync();
        Task SaveAsync(StartupConfig config);
    }

    public class StartupConfigService : IStartupConfigService
    {
        private readonly ILogger<StartupConfigService> _logger;
        private readonly string _configPath;
        private StartupConfig? _config;

        public StartupConfigService(ILogger<StartupConfigService> logger)
        {
            _logger = logger;
            // Path to config.json in the application config directory
            // For published executables, use the base directory (publish folder)
            // For development, this will be adjusted by the content root path logic in Program.cs
            _configPath = Path.Combine(AppContext.BaseDirectory, "config", "config.json");
            Load();
        }

        private void Load()
        {
            try
            {
                if (!File.Exists(_configPath))
                {
                    _logger.LogInformation("Startup config not found at {Path}, creating default config", _configPath);
                    _config = CreateDefaultConfig();
                    SaveDefaultConfig();
                    return;
                }

                var json = File.ReadAllText(_configPath);
                _config = JsonSerializer.Deserialize<StartupConfig>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to load startup config from {Path}", _configPath);
                _config = new StartupConfig();
            }
        }

        public StartupConfig? GetConfig() => _config;

        public Task ReloadAsync()
        {
            Load();
            return Task.CompletedTask;
        }

        public Task SaveAsync(StartupConfig config)
        {
            try
            {
                var options = new JsonSerializerOptions { WriteIndented = true };
                var json = JsonSerializer.Serialize(config, options);
                // Attempt to write to the same path we read from
                File.WriteAllText(_configPath, json);
                _config = config;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to save startup config to {Path}", _configPath);
                throw;
            }

            return Task.CompletedTask;
        }

        private StartupConfig CreateDefaultConfig()
        {
            return new StartupConfig
            {
                // Basic configuration with sensible defaults
                LogLevel = "Information",
                EnableSsl = false,
                Port = 5000,
                SslPort = 6868,
                UrlBase = "/",
                BindAddress = "*",
                ApiKey = null, // Will be generated by user
                AuthenticationMethod = "None",
                AuthenticationRequired = "Disabled",
                UpdateMechanism = "BuiltIn",
                LaunchBrowser = true,
                Branch = "main",
                InstanceName = "Listenarr",
                SyslogPort = null,
                AnalyticsEnabled = false,
                SslCertPath = null,
                SslCertPassword = null,
                Ffmpeg = new FfmpegConfig
                {
                    Provider = "gyan", // Default to gyan.dev for Windows
                    ReleaseOverride = null,
                    ChecksumUrl = null,
                    Arch = null
                }
            };
        }

        private void SaveDefaultConfig()
        {
            try
            {
                // Ensure the config directory exists
                var configDir = Path.GetDirectoryName(_configPath);
                if (!string.IsNullOrEmpty(configDir) && !Directory.Exists(configDir))
                {
                    Directory.CreateDirectory(configDir);
                }

                var options = new JsonSerializerOptions { WriteIndented = true };
                var json = JsonSerializer.Serialize(_config, options);
                File.WriteAllText(_configPath, json);
                _logger.LogInformation("Default config.json created at {Path}", _configPath);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to save default config to {Path}", _configPath);
            }
        }
    }
}
